# Generated by Django 4.2.6 on 2023-10-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calories', models.IntegerField()),
                ('proteins', models.IntegerField()),
                ('lipids', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
