# Generated by Django 4.2.6 on 2023-10-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_remove_recipe_calories_remove_recipe_lipids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.IntegerField(null=True),
        ),
    ]
