# Generated by Django 4.2.6 on 2023-10-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_preparation_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={},
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Meal', 'Meal'), ('Collation', 'Collation')], default='Meal', max_length=50),
        ),
    ]
