# Generated by Django 4.2.6 on 2023-10-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='carbohydrates',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('WEIGHT', 'Weight'), ('PORTION', 'Portion')], default='WEIGHT', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='items'),
        ),
    ]
