# Generated by Django 4.2.6 on 2023-10-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='carbohydrates',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='lipids',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='proteins',
            field=models.FloatField(),
        ),
    ]
