name: Deploy DRF Backend to OVH VPS

on:
  push:
    branches:
      - main # or whichever branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Rsync backend directory and Deploy to VPS using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          rsync -avz --delete nutritionAppBackend/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/var/www/backend/
          cd /var/www/backend
          source venv/bin/activate # Activate virtual environment if you're using one.
          pip install -r requirements.txt # Install dependencies.
          python manage.py migrate # Apply migrations.
          # Restart your server, e.g., 
          systemctl restart gunicorn
