name: Deploy to OVH VPS

on:
  push:
    branches:
      - main  # Adjust this if you're deploying from a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client

    - name: Setup SSH Key and Set SSH Strict Host Checking to No
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        echo "Host *" >> ~/.ssh/config
        echo "  IdentityFile $(pwd)/private_key" >> ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        chmod 600 ~/.ssh/config

    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i"
        SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
        EXCLUDE: "/dist/, /node_modules/"
        SCRIPT_BEFORE: |
          whoami
          ls -al
        SCRIPT_AFTER: |
          whoami
          ls -al
          echo $RSYNC_STDOUT
          
    - name: Install and Setup Project on VPS
      run: |
        ssh ubuntu@51.77.203.206 <<'ENDSSH'
        cd /var/www/backend/
        source venv/bin/activate
        pip install -r requirements.txt
        python manage.py migrate
        # Restart services like Gunicorn and Nginx if needed
        sudo systemctl restart gunicorn
        sudo systemctl restart nginx
        ENDSSH
